/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define HAVE_ATEXIT 1

#define HAVE_GETPAGESIZE 1

#define HAVE_ISATTY 1

#define HAVE_MMAP 1

#define HAVE_MPROTECT 1

#define HAVE_NEWLOCALE 1

#define HAVE_PTHREAD 1

#define HAVE_SINCOS 1

#define HAVE_SINCOSF 1

#define HAVE_STDBOOL_H 1

#define HAVE_SYSCONF 1

#define HAVE_SYS_MMAN_H 1

#define HAVE_UNISTD_H 1

#define HAVE_USELOCALE 1

#define HAVE_XLOCALE_H 1

